
###
GET http://localhost:5000/games


###
GET http://localhost:5000/games/fe949393-e988-4d94-bbee-4093a533bdfb


###
POST http://localhost:5000/games
Content-Type: application/json

{
  "name": "new game",
  "genreId": "e5f67890-a1b2-c3d4-e5f6-7890a1b2c3d4",
  "price": 21,
  "releaseDate": "2022-11-09",
  "description": "new description"
}

###
PUT localhost:5000/games/fe949393-e988-4d94-bbee-4093a533bdfb
Content-Type: application/json

{
  "name": "Test Updated",
  "genreId": "e5f67890-a1b2-c3d4-e5f6-7890a1b2c3d4",
  "price": 121,
  "releaseDate": "2025-11-09",
  "description": "updated description"
}

### 
DELETE http://localhost:5000/games/fe949393-e988-4d94-bbee-4093a533bdfb


###
GET localhost:5000/genres